// swift-tools-version: 5.10
// The swift-tools-version declares the minimum version of Swift required to build this package.
import PackageDescription

let package = Package(
    name: "dlist",
    dependencies: [
        .package(url: "https://github.com/smittytone/clicore", branch: "main"),
    ],
    targets: [
        .executableTarget(
            name: "dlist",
            dependencies: [
                .product(name: "Clicore", package: "clicore"),
                .target(name: "Clibudev", condition: .when(platforms: [.linux])),
            ],
            path: "dlist",
            exclude: [
                // `Info.plist` is not a Swift source file, so its must be excluded
                // from macOS or Linux builds generated by calling the Swift compiler
                "Info.plist"
            ]
        ),
        .systemLibrary(
            name: "Clibudev",
            path: "clibudev",
            pkgConfig: "libudev"
        )
    ]
)
